apiVersion: v1
kind: Service
metadata:
  labels:
    whatsdown.service: locationservice
  name: locationservice
  namespace: whatsdown
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    whatsdown.service: locationservice