apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: whatsdown-mq
  namespace: whatsdown
spec:
  replicas: 1
  resources:
    limits:
      # cpu: 2
      memory: "256Mi"
  rabbitmq:
    additionalConfig: |
      vm_memory_high_watermark.relative = 0.7
      disk_free_limit.absolute = 50MB
      collect_statistics_interval = 10000
      default_user= guest 
      default_pass = guest
      
  persistence:
    storage: "300Mi"
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []