apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: whatsdown-mq
  namespace: whatsdown
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: whatsdown-mq
---