apiVersion: v1
kind: Service
metadata:
  labels:
    whatsdown.service: messageservice

  name: messageservice
  namespace: whatsdown
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6021
    targetPort: 80
    protocol: TCP
  - name: "https"
    port: 6022
    targetPort: 443
    protocol: TCP
  selector:
    whatsdown.service: messageservice
status:
  loadBalancer: {}