apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: messageservice--db-data
  namespace: whatsdown
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}