apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: messageservice
  namespace: whatsdown
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: messageservice
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50