apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatsdown-ingress
  namespace: whatsdown
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: "messageservice"
    
spec:
  rules:
  - host: whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: whatsdownfrontend
            port: 
              number: 4200  
#temp for debug only:
  - host: authservice.whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: authservice
            port: 
              number: 6001
  - host: locationservice.whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: locationservice
            port: 
              number: 6031  
  - host: api.whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: whatsdownbackend
            port: 
              number: 6011  
  - host: friendservice.whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: friendservice
            port: 
              number: 6041  

  - host: messageservice.whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: messageservice
            port: 
              number: 6021  
  - host: profileservice.whatsdown.nl
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: profileservice
            port: 
              number: 6051  
  - host: mq.whatsdown.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whatsdown-mq
            port: 
              number: 15672