apiVersion: v1
kind: Service
metadata:
  labels:
    whatsdown.service: authservice

  name: authservice
  namespace: whatsdown
spec:
  type: ClusterIP
  ports:
  - name: "http"
    port: 6001
    targetPort: 80
    protocol: TCP
  - name: "https"
    port: 6002
    targetPort: 443
    protocol: TCP
  selector:
    whatsdown.service: authservice
status:
  loadBalancer: {}