apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    whatsdown.service: authservice-db
    app: authservice
    version: "1.0"
  name: authservice-db
  namespace: whatsdown
spec:
  replicas: 1
  selector:
    matchLabels:
      whatsdown.service: authservice-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        whatsdown.service: authservice-db
        app: authservice
        version: "1.0"
    spec:
      containers:
      - image: mysql:8.0.24
        imagePullPolicy: IfNotPresent
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_DATABASE
          value: TestDB
        - name: MYSQL_PASS
          value: password
        - name: MYSQL_PASS
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: root
        name: authservice-db
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: authservice-db-data
      hostname: authservice-db
      restartPolicy: Always
      volumes:
      - name: authservice-db-data
        persistentVolumeClaim:
          claimName: authservice-db-data