apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authservice-db-data
  namespace: whatsdown
spec:
  storageClassName: "manual"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}