apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    whatsdown.service: authservice
  name: authservice
  namespace: whatsdown
spec:
  replicas: 1
  selector:
    matchLabels:
      whatsdown.service: authservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        whatsdown.service: authservice
    spec:
      containers:
      - image: noonespecial123/whatsdown_auth:latest
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_URLS
          value: http://+:80 
        name: whatsdown-authservice
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
      hostname: authservice
      restartPolicy: Always