apiVersion: v1
kind: Service
metadata:
  labels:
    whatsdown.service: authservice-db
  name: authservice-db
  namespace: whatsdown
spec:
  type: ClusterIP
  ports:
  - name: "authservice-db"
    protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    whatsdown.service: authservice-db