apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    whatsdown.service: friendservice-db
    app: friendservice
    version: "1.0"
  name: friendservice-db
  namespace: whatsdown
spec:
  replicas: 1
  selector:
    matchLabels:
      whatsdown.service: friendservice-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        whatsdown.service: friendservice-db
        app: friendservice
        version: "1.0"
    spec:
      containers:
      - image: mysql:8.0.24
        imagePullPolicy: IfNotPresent
        args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        name: friendservice-db
        ports:
        - containerPort: 3307
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: friendservice-persistent-storage
      hostname: friendservice-db
      restartPolicy: Always
      volumes:
      - name: friendservice-persistent-storage
        persistentVolumeClaim:
          claimName: friendservice-pv-claim